apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: test-1
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
---
apiVersion: v1
kind: Pod
metadata:
  namespace: test-2
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-other-namespaces
  namespace: test-2
spec:
  podSelector: {}  # Selects all pods in the namespace
  policyTypes:
  - Ingress
  ingress:
  # Allow traffic only from within the same namespace
  - from:
      - namespaceSelector: {}  # Only allows traffic from within test-2 namespace

