apiVersion: v1
kind: Namespace
metadata:
  name: test-1
  labels:
    project: test-1
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-2
  labels:
    project: test-2
    environment: dev