apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-access-sa
  namespace: test-1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-access-role
  namespace: test-1
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-access-rolebinding
  namespace: test-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-access-role
subjects:
- kind: ServiceAccount
  name: secret-access-sa
  namespace: test-1
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-reader
  namespace: test-1
spec:
  serviceAccountName: secret-access-sa
  containers:
  - name: secret-reader
    image: alpine
    command: ["sh", "-c", "sleep 3600"]